site_name: kopimi.datapor.no
repo_url: https://github.com/skandix/kopimi.datapor.no
repo_name: kopimi.datapor.no
extra_css:
  - stylesheets/extra.css
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
# plugins:
#   - search:
#       indexing: 'full'
theme:
  name: material
  font: true
  locale: "no"
  highlightjs: true
  features:
    - navigation.instant
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - header.autohide
  markdown_extensions:
    toc:
      permalink: "#"
      baselevel: 1
    sane_lists: {}
    admonition: {}